version: '3.8'

services:
    cms_mongo_docker:
        image: nestjs-api-dev:1.0.0
        build:
            context: .
            target: development
            dockerfile: ./Dockerfile
        command: npm run start:debug
        env_file: 
            - .env
        ports:
            - 3000:3000
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        restart: unless-stopped
        depends_on: 
            - mongodb
    mongodb:
        image: mongo:latest
        restart: always
        volumes: 
            - data:/data/db
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root

volumes: 
    data: